# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://yoursite.com
title: Netsource Interactive
email: your-email@domain.com
author: Jinlong
description: This is Jinlong's testing site
copyright: 'Copyright &copy; 2016 Netsource Interactive Inc. All Rights Reserved.'
credits:

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: twitter
    url:
  - title: github
    url:
  - title: linkedin
    url: 
